### ISSUE TITLE
character mask

### ISSUE THREAD

**Issue by yussan** [yussan/npm-string-manager#28]
## Proposal
```
characterMask()
```

## Sample 1
* **argument**
  "yussan@gmail.com"
* **result**
   "y*****@*****.com"

## Sample 2
* **argument**
   "this is text"
* **result**
   "this is ****"

**Comment by nitingupta89** [comment]
How do you want it to be implemented?

**Comment by nitingupta89** [comment]
A brief description would be helpful

**Comment by yussan** [comment]
sorry @nitingupta89 this issue is not for `hacktoberfest`, assignment to internal tim by @dzhurey .

**Comment by nitingupta89** [comment]
ok

**Comment by dzhurey** [comment]
maybe we can use some parameter for this function:
1. String to masked
2. Range masked
3. Character exception

**Comment by yussan** [comment]
@dzhurey can you show how to use and result expectation here
